FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install
#Generate Prisma Client
RUN npm run db:generate
#Build only user-app using Turbo filter
RUN npm run build --filter=user-app

CMD ["npm", "run", "start-user-app"]